name: Build Application
on: [pull_request, workflow_dispatch]

env:
  NODE_VERSION: 20.x

jobs:
  build:
    name: Build application with Node.js
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›ï¸ Checkout Repository
        uses: actions/checkout@v3

      - name: â˜ï¸ Restore Yarn Cache
        uses: actions/cache/restore@v3
        with:
          path: ~/.cache/yarn/v6
          key: node-cache-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            node-cache-${{ runner.os }}-yarn-

      - name: âš™ï¸ Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: ğŸ”§ Install Server Dependencies
        run: yarn install --frozen-lockfile

      - name: ğŸ”§ Install Client Dependencies
        run: cd client && yarn install --frozen-lockfile

      - name: ğŸ—ï¸ Build Application
        run: yarn build
