name: Cache Yarn
on:
  schedule:
    # Every Sunday at 00:00 UTC+7
    - cron: "0 17 * * 6"
  workflow_dispatch:

env:
  NODE_VERSION: 20.x

jobs:
  cache:
    name: Cache with Node.js
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Yarn
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn/v6
          key: node-cache-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            node-cache-${{ runner.os }}-yarn-

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Server Dependencies
        run: yarn install --frozen-lockfile
        
      - name: Install Client Dependencies
        run: cd client && yarn install --frozen-lockfile
